#!/bin/bash
# Note: AI generated by gemini

# Define formatting for the table output
# %-30s means left-align string with 30 chars width
FORMAT="%-30s | %-10s\n"

# Print Table Header
printf "$FORMAT" "Test Name" "Exit Code"
echo "-------------------------------+-----------"

# Loop through all .pas files in the current directory
for source_file in *.pas; do
    
    # Handle case where no .pas files exist
    [ -e "$source_file" ] || continue

    # Extract the filename without the extension (e.g., test1.pas -> test1)
    test_name="${source_file%.*}"

    # 1. Compile with Free Pascal (fpc)
    # -v0 suppresses the fpc logo and verbose messages to keep stdout clean
    # We redirect compiler output to /dev/null so it doesn't clutter the table
    if fpc -v0 "$source_file" > /dev/null 2>&1; then
        
        # 2. Run the executable
        # Redirect stdout to the golden file
        # Stderr is left visible (or you can redirect it to /dev/null)
        ./"$test_name" > "${test_name}.golden"
        
        # 3. Capture the exit code of the executable
        exit_code=$?
        
        # 4. Print the row in the table
        printf "$FORMAT" "$test_name" "$exit_code"

        # 5. Cleanup (Optional)
        # fpc creates an executable and an object file (.o). 
        # We remove them to keep the directory clean.
        rm -f "$test_name" "${test_name}.o" 

    else
        # If fpc failed to compile
        printf "$FORMAT" "$test_name" "COMPILE ERR"
    fi

done
